//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunskoolApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FunskoolDbEntities : DbContext
    {
        public FunskoolDbEntities()
            : base("name=FunskoolDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ManufacturePlant> ManufacturePlants { get; set; }
        public virtual DbSet<ToyCategory> ToyCategories { get; set; }
        public virtual DbSet<Toy> Toys { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<orderDetail> orderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PlaceOrder> PlaceOrders { get; set; }
        public virtual DbSet<ShippingOrder> ShippingOrders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vGetOrderDetail> vGetOrderDetails { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
    }
}
