//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunskoolApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGetOrderDetail
    {
        public string name { get; set; }
        public string ToyName { get; set; }
        public decimal Price { get; set; }
        public string FullName { get; set; }
        public string mobileNumber { get; set; }
        public string Address { get; set; }
        public string LocatedPlant { get; set; }
        public string State { get; set; }
        public int OrderDetail { get; set; }
    }
}
